### ISSUE TITLE
Linux install does not work

### ISSUE THREAD

**Issue by Gtach** [rolandshacks/vs64#33] opened 2023-01-30 17:57 UTC
Installed VS64 2.02 on Ubuntu 22.10 and VC 1.74.3

acme, cc65 and vice installed. paths in settings updated (/usr/bin/acme, /usr/bin/cc65)

Command to create project produces:
'Command 'VS64: Create ACME Assembler Project' resulted in an error (command 'vs64.createProjectAsm' not found)

Opening example folder with main.asm generates:
 *  Executing task: build example 
Error: spawn ENOTDIR

When trying to run: No example.report created in build folder.

**Comment by rolandshacks** [comment] 2023-01-30 18:02
Thank you for the report. Will immediately have a look.

**Comment by rolandshacks** [comment] 2023-01-30 21:25
Ok. This is not a bug, but a not well handled mistake in the settings - which I should fix and improve soon.
Both mentioned settings (acme and cc65 - and also llvm) are installation DIRECTORIES which need to be set if they are not the default. For a usual Linux installation, just leave it blank and it should be fine. In case you used the Getting Started wizard, you can just tick off the settings steps.

As said before, thanks for the feedback - I will think about how to make this more robust.

Please clear the settings for acme and cc65, try again and let me know if things are fine now.

**Comment by Gtach** [comment] 2023-01-31 08:32
Right, that was fast, and it worked. I removed the settings to blank paths and things started to work. Nice
I also created a launch config and got the example program to run in vice.
Many thanks, :-)
Btw, I plan to have a big C64 program (36k assembler) from 1988 converted to cross assembling. I have no idea how all my tools from 35 years ago work anymore, so better start with improved setup in 2023. :-) I will use this setup to see if it holds up. If something comes up I will contact you. Now to get those assembly files from the C64 to Linux...
Thanks for the help

**Comment by rolandshacks** [comment] 2023-01-31 08:51
Hey, glad it worked.

Your project sounds super interesting. Let me know if you need something,
I'll be more than happy to check if I can easily add features
"just-in-time".
(Unfortunately, I am not a great 6502 assembly coder, it was never my
strength ... and these days, working on AI, robo taxis, etc. doesn't
include much of that ... and in the past, I just couldn't affort the right
amount of books, and stuff you need ...) But, I am really fascinated by the
idea of applying exactly what is used for large scale software to retro
projects... And IDE support, debuggers, maybe some kind of resource
compilers, etc. are fun to do (well, the debugger for ELF/DWARF isn't
really...).

My focus moved on to the LLVM-MOS tookit, just to get C++ 20 (and Rust)
going - to see how a hybrid setup of asm and c++ would look like... Maybe
that would also be something for you to have a look ?

Cheers!
Roland

Am Di., 31. Jan. 2023 um 09:32 Uhr schrieb Gtach ***@***.***>:

**Comment by amelco** [comment] 2023-02-01 00:22
Same (probably) issue but in windows with vanilla vscode (fresh install, no extensions).

I installed VS64 v2.0.2 in VS Code 1.74.3. I did not have ACME Cross Assembler installed. Only VICE emulator.
I noticed that the button "Update Settings" in "Get Started" window did not work. I could go into settings clicking on the gear icon on the side of extension icon and updated the path to ACME (after installation) and VICE.

I tried to ctrl+shift+p VS64: Create Acme Assembler Project and got the error:
'Command 'VS64: Create ACME Assembler Project' resulted in an error (command 'vs64.createProjectAsm' not found)

Similar error also occur when I try every other option from the ctrl+shift+p menu for the extension. For instance, trying "Getting Started" returns command 'vs64.showWelcome' not found.

I've tried to clean all configuration options without success. Also tried to uninstall/reinstall both extension and vscode.

**Comment by rolandshacks** [comment] 2023-02-01 07:29
Hi. Thanks for the update.
This is really strange, will look at it asap.

Am Mi., 1. Feb. 2023 um 01:22 Uhr schrieb Andre Herman F. Bezerra <
***@***.***>:

**Comment by rolandshacks** [comment] 2023-02-01 08:19
Could you please do me a favor and try once again, but now with log level
of vs64 set to "trace" and the developer tools turned on in Visual Studio
Code?
(You do this using the "Command Palette" -> "Toggle Developer Tools")

THANKS a lot in advance!
Roland


Am Mi., 1. Feb. 2023 um 08:29 Uhr schrieb Roland Schabenberger <
***@***.***>:

**Comment by rolandshacks** [comment] 2023-02-01 09:47
Another option: could it be that you did not create a workspace? (like, not
having opened a folder?)

Am Mi., 1. Feb. 2023 um 09:18 Uhr schrieb Roland Schabenberger <
***@***.***>:

**Comment by rolandshacks** [comment] 2023-02-01 10:03
Well, I think that's the problem: In case there's no workspace (folder
opened) - the extension does not register completely.
Workaround: open a folder, restart vscode

I consider this to be a bug and will fix asap.


Am Mi., 1. Feb. 2023 um 10:47 Uhr schrieb Roland Schabenberger <
***@***.***>:

**Comment by rolandshacks** [comment] 2023-02-01 16:55
Should be fixed with release v2.0.3
(Release has been published on vscode marketplace)

Please check and re-open in case the problem is not gone.
THANK YOU!!

**Closed by rolandshacks** 2023-02-01 16:55 UTC

**Comment by amelco** [comment] 2023-02-01 17:25
Wow! Thanks for the quick response and update.
I will check if the problem persists and, if so, I'll reopen this and give you the information you asked.
