### ISSUE TITLE
Using a printer with C64 BASIC crashes VICE

### ISSUE THREAD

**Issue by clouddistortion** [rolandshacks/vs64#71] opened 2024-05-25 11:39 UTC
Hi,
I tried the following main.bas
```
OPEN4,4
PRINT#4,"Ergebnisse:"
CLOSE4
```
My Vice printer settings looks like this:
<img width="938" alt="vice_printer_settings" src="https://github.com/rolandshacks/vs64/assets/5367146/9ed53dcb-2c11-42b6-9da3-f15c2672ae82">

**Problem**
If I run the program via VS64 with VICE 3.8 gtk, VICE crashes. (also tried release in the project settings)

If I put the prg into a D64 image via
`/Applications/vice-x86-64-gtk3-3.8/bin/c1541 -format "mg64,mg" d64 build/test.d64 -attach build/test.d64 -write build/test.prg` and then run the image manually everything works

**My guess**
Possibly its linked to how VICE is started via VS64 because if I run VICE via VS64 and manually type the BASIC commands in, VICE crashes too. If I start VICE without VS64 I don't have the problem

**Comment by rolandshacks** [comment] 2024-07-23 14:14
This can be connected to the known bug of vice which causes problems (crashes) when a debugger is connected. That specific bug does NOT exist on the SDL version of vice.

**Comment by rolandshacks** [comment] 2024-10-20 06:56
Closing this issue now because it is a duplicate of the other issues (like #68)

**Closed** 2024-10-20 06:56 UTC
Labels: bug
